//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFPSLib.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IFPSLib.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CompiledCode {
            get {
                object obj = ResourceManager.GetObject("CompiledCode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CompiledCode_v22 {
            get {
                object obj = ResourceManager.GetObject("CompiledCode_v22", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .version 23
        ///
        ///.entry !MAIN
        ///
        ///.type primitive(Pointer) Pointer
        ///.type primitive(U32) U32
        ///.type primitive(Variant) Variant
        ///.type primitive(PChar) PChar
        ///.type primitive(Currency) Currency
        ///.type primitive(Extended) Extended
        ///.type primitive(Double) Double
        ///.type primitive(Single) Single
        ///.type primitive(S64) S64
        ///.type primitive(String) String
        ///.type primitive(U32) U32_2
        ///.type primitive(S32) S32
        ///.type primitive(S16) S16
        ///.type primitive(U16) U16
        ///.type primitive(S8) S8
        ///.type(export) funcptr(void()) ANY [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompiledCodeDisasm {
            get {
                return ResourceManager.GetString("CompiledCodeDisasm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .version 23
        ///
        ///.entry !MAIN
        ///
        ///.type primitive(Pointer) Pointer
        ///.type primitive(U32) U32
        ///.type primitive(Variant) Variant
        ///.type primitive(PChar) PChar
        ///.type primitive(Currency) Currency
        ///.type primitive(Extended) Extended
        ///.type primitive(Double) Double
        ///.type primitive(Single) Single
        ///.type primitive(S64) S64
        ///.type primitive(String) String
        ///.type primitive(U32) U32_2
        ///.type primitive(S32) S32
        ///.type primitive(S16) S16
        ///.type primitive(U16) U16
        ///.type primitive(S8) S8
        ///.type(export) funcptr(void()) ANY [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompiledCodeDisasm_v22 {
            get {
                return ResourceManager.GetString("CompiledCodeDisasm_v22", resourceCulture);
            }
        }
    }
}
